### PR TITLE
Sort imports

### PR DESCRIPTION
**Pull request by cdupuis**
@ddgenome I've enabled a plugin to sort imports in our TS code. Let me know what you think about this change. If we like this, I would change our eslint-skill configuration to roll out that change and close this PR here.

I'm not too sure about the empty line between module and relative imports. But the rest of the sorting is a good addition IMHO so I'm willing to live with the empty line.

### CODE REVIEW

**Review by ddgenome — APPROVED** [review]
This looks good to me.

According to the [docs](https://github.com/lydell/eslint-plugin-simple-import-sort/#imports), if you use import/first, it will put all imports in the same "chunk".

**Comment by cdupuis** [comment]
What do you prefer? With or without the empty line?

**Comment by ddgenome** [comment]
I do not have a strong opinion either way. Since we used to put the space between absolute and relative imports and now we do not, I've acclimatized to both.

**Comment by ddgenome** [comment]
Did you not want to merge this?

**Comment by cdupuis** [comment]
I wanted to test the skill config on this repository here: https://github.com/atomist-skills/skill/pull/164

**Pull request closed without merging**
